### PR TITLE
Fix truncated byte (issue #35)

### PR DESCRIPTION
**Pull request by HawkLiking**
This should do the job to solve issue #35 

Tested with file sizes / threads from #35 , and with more than 10000 size/thread configuration.

### CODE REVIEW

**Comment by iTaybb** [comment]
Nice catch. Let me inspect it and I'll merge it soon.

**Comment by iTaybb** [comment]
So, few notes:
1. The rounding issue is from the python2 ages. Thanks for that. Please also implement the rounding on the loop before that (line 682)

2. I wonder regarding the fix of the `filesize-1`.
Since this issue seems to be an off-by-one issue, it might be the solution. However I'm quite baffled:
since the bytes count goes from `0` to `filesize-1` (inclusive), we cannot request byte `filesize`.
For example, if we're downloading a 5 bytes file, we would request bytes 0 to 4. Requesting byte would be an error.

What do you think?

**Comment by HawkLiking** [comment]
Yes you are totally right, the `filesize-1` to `filesize` won't fix anything !

I will push a correction  :)

**Comment by HawkLiking** [comment]
Done

And I also round the filesize/threads in the while (threads number verification) like you said before editing yourpost, I think it is indeed good to check with the chunck size we will have just after with the same round

**Pull request merged**
